# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b5837399e393397076da53976d7343e667fca8e388b34e8b8d566f910bfdad97a65b4bf3130f464130396c6b4af6bb7454e27dea33a86a4c36226415b57f106

test:
  secret_key_base: cebc969f75e97a17501a3ba1554a610165489fe48b6b0c3a4106b1396140965f430764386735a3bc3def8e0b8f2be1e7a67c7551fb674f108da1f71cd6ad6e85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
